# Generated by Django 6.0 on 2025-12-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Delivery", "0002_menu"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
