# Generated by Django 6.0 on 2026-01-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Delivery", "0003_delete_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("restaurant", "Restaurant"),
                    ("delivery", "Delivery"),
                    ("admin", "Admin"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
